### ISSUE TITLE
pageText fails on CNN articles

### ISSUE THREAD

**Issue by gregobad** [mozilla-rally/web-science#163]
Our extension (https://code.stanford.edu/gjmartin/beyond_the_paywall) uses pageText.content.js to extract full text of news articles. It consistently fails, returning an empty string, on articles from cnn.com. Here is an example:

https://www.cnn.com/2021/10/08/politics/white-house-privilege-january-6-committee/index.html

My guess is the unusual URL format (with index.html at the end) trips up the isArticle check.

**Comment by rhelmer** [comment]
> The WebScience `pageText` module relies on [Mozilla Readability](https://github.com/mozilla/readability) to parse articles. That library is the de facto standard for article parsing in JavaScript. And, unfortunately, it appears to have a years-old incompatibility with detecting articles on CNN.com owing to unusual `<div>` formatting: [mozilla/readability#420](https://github.com/mozilla/readability/issues/420).
> 
> The good news is, this issue is probably easy to fix. Readability operates in two passes: a fast heuristic to determine whether the webpage is likely an article that can be parsed, followed by a slow parsing step. The issue on CNN.com is solely with the heuristic; I confirmed that parsing works fine, other than some punctuation formatting oddities.
> 
> We could easily add a dataset of URL match patterns that we know are likely articles and that are false negatives for the Readability heuristic. If a webpage loads with a URL that matches the dataset, we would skip the heuristic step and immediately invoke article parsing. We need to update how `pageText` handles article detection anyway, because our current approach relies a Firefox-specific API for the Readability heuristic: https://github.com/mozilla-rally/web-science/blob/main/src/pageText.js#L190.
> 
> @rhelmer, thoughts?

@jonathanmayer I think this would work, but can we do it without needing to maintain the "fails heuristic but actually parses" dataset of URLs? Would it be harmful is it to skip the fast heuristic step (`isProbablyReaderable`) and always run the slow parsing step?

**Comment by jonathanmayer** [comment]
My assumption has been that we don't want to incur the performance penalty of parsing unless we have some confidence that it'll work. But maybe that assumption was wrong. From some very quick and ad hoc testing, the heuristic step is ~1ms and the parsing step is ~50-100ms on my 6.5-year-old notebook. That might be tolerable, especially if we use `requestIdleCallback`.
