### ISSUE TITLE
detecting page unload from content script is unreliable in Chrome

### ISSUE THREAD

**Issue by rhelmer** [mozilla-rally/web-science#238]
Per discussion in https://github.com/mozilla-rally/web-science/issues/114#issuecomment-1100225683:

> From my testing so far and discussion and discussion in [#addons on matrix](https://matrix.to/#/!CuzZVoCbeoDHsxMCVJ:mozilla.org/$ItXwR-2GCjDQIOEAn6lrYhyVh7kLWbfC7qiciqYVmwU?via=mozilla.org&via=matrix.org&via=perthchat.org), there isn't a reliable way to do this from the content script. I tested with unload which fired unreliably, also with pagehide and visibilitychange which didn't fire at all.

To make this work with Chrome in the near-term I think we need to use an API from the background to listen to this, such as listening to changes in tabs. To support manifest v3, we should do this in a way that will work with service workers so we should not assume we have access to a persistent background page.

**Comment by jonathanmayer** [comment]
Possibly relevant: https://bugs.chromium.org/p/chromium/issues/detail?id=1144856

Could you say more about the testing setup? Also worth looking at the `popstate`, `freeze`, and `resume` events. Another workaround to consider is listening for these events with a script injected into the page, if the ordinary content process handles the events correctly.

**Comment by rhelmer** [comment]
> Possibly relevant: https://bugs.chromium.org/p/chromium/issues/detail?id=1144856
> 
> Could you say more about the testing setup?

I'll make a minimal test case, but basically I am just putting [debugger](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/debugger) statements into the content script, opening devtools on the site, and observing when it does/doesn't fire in the devtools debugger. I also have the serviceworker logging messages and it's not receiving them (note that I haven't tested this with manifest v2 just v3 under Chrome).

> Also worth looking at the `popstate`, `freeze`, and `resume` events. Another workaround to consider is listening for these events with a script injected into the page, if the ordinary content process handles the events correctly.

I'll try these, thanks. Injecting into the content process is an interesting idea, although I think getting the message back to the extension will be trickier.

**Comment by rhelmer** [comment]
OK here's a branch with two commits: one where I've added a test case for manifest v2, and then a second commit which updates it to manifest v3:

https://github.com/mozilla-rally/web-science/compare/main...rhelmer:testcase-for-issue-238?expand=1

It can be used by calling `rollup -c rollup.config.js` and then run with `web-ext run -t chromium`.

And actually testing this, it seems like `unload` is firing consistently when I close tabs. I see `pageNavigation` and `pageManager` firing as I'd expect when I navigate back as well (looks like this is handled by `browser.webNavigation.onHistoryStateUpdated.addListener` in `pageManager` which fires `pageVisitStop`, so that's fine), so maybe I'm wrong about the problem here. I'm not sure why this is different than the behavior I'm seeing in my extension but I'll look into it further.

**Comment by rhelmer** [comment]
> And actually testing this, it seems like `unload` is firing consistently when I close tabs. I see `pageNavigation` and `pageManager` firing as I'd expect when I navigate back as well (looks like this is handled by `browser.webNavigation.onHistoryStateUpdated.addListener` in `pageManager` which fires `pageVisitStop`, so that's fine), so maybe I'm wrong about the problem here. I'm not sure why this is different than the behavior I'm seeing in my extension but I'll look into it further.

OK I'm actually seeing it work fine in a controlled environment (local webserver, standard set of tests etc) but I see it break when I use it in the wild. I'll figure out a reproducible test case.

**Comment by rhelmer** [comment]
https://developer.chrome.com/blog/page-lifecycle-api/ is a good reference for Chrome, although I am finding some inconsistencies:

- `visibilitychange` fires on both `window` and `document`
- I haven't observed a `freeze` event fire

`visibilitchange` fires whenever the tab loses focus.

`pagehide`on `window` seems to be the closest to what we want, it appears fires before `unload` (which fires inconsistently).

> Possibly relevant: https://bugs.chromium.org/p/chromium/issues/detail?id=1144856
> 
> Could you say more about the testing setup? Also worth looking at the `popstate`, `freeze`, and `resume` events. Another workaround to consider is listening for these events with a script injected into the page, if the ordinary content process handles the events correctly.

Thanks! I think we're OK on `popstate` because the way we watch tabs for history changes, as mentioned above `freeze` doesn't seem to fire in any case, but I'll look into that further since it's pretty much what we want.

I'll figure out the best workaround in the meantime, but we should consider aligning more closely to the page lifecycle API - however I think we'll run into cross-browser issues no matter what trying to do this from the content script, so using the `tabs.onChange` or similar APIs from the extension is probably a more reliable way to detect when page visits end.
