### ISSUE TITLE
[Epic] Robust Chrome + MV3 support

### ISSUE THREAD

**Issue by aaga** [mozilla-rally/web-science#313]
This ticket is to track progress on action items that came from [this meeting](https://docs.google.com/document/d/1DDdSYtjqZphsr6YFvivxPYP8OwPrvdynj5IePWOqZrc/edit#heading=h.q4zcrxrkstvh) with Jonathan Meyer.

TODO: chunk up into tasks and prioritize

**Comment by marniepw** [comment]
Closing as part of the Rally wind down.
