### ISSUE TITLE
enable stricter eslint rules

### ISSUE THREAD

**Issue by rhelmer** [mozilla-rally/web-science#32]
I'm not sure what the gold standard is nowadays, but we should ratchet it up a bit, like always requiring braces around if/then/else statements and other potential safety issues.

I'm less concerned about style in general but it'd be nice to pick something comprehensive instead of a ruleset we need to maintain, since it's not very productive to argue about style nits in reviews :)

**Comment by jonathanmayer** [comment]
https://github.com/dustinspecker/awesome-eslint

🤷‍♂️

**Comment by hamilton** [comment]
I personally would opt for [the Airbnb rules](https://www.npmjs.com/package/eslint-config-airbnb) which I've used in the past. Many sensible defaults, and we can turn off the ones that are not joyful for us.

**Comment by jonathanmayer** [comment]
Fine by me.
