### ISSUE TITLE
add additional features to the messaging schema validation

### ISSUE THREAD

**Issue by hamilton** [mozilla-rally/web-science#33]
The schema validation part of the `Messaging` is a great way to catch errors at the point of reporting from content scripts. It is, however, missing some features that would enable more sophisticated use in future studies:

- there is no way to mark a field as `optional` or alternatively specify which are `required`
- there is no way to specify more than one type

Some possibilities:
1. build these two features into the current schema validation. It wouldn't be too hard to take the syntax from json schema and implement those here.
2. use a well-tested / pre-existing schema validation library like `ajv`

**Comment by jonathanmayer** [comment]
> use a well-tested / pre-existing schema validation library like ajv

I like this idea. We developed the current schema system as an ad hoc means of minimizing foreseeable bugs. Switching to a standard schema system and library should be (relatively) painless, since our schemas are simple and we can integrate a library into the build.
