### ISSUE TITLE
release v0.1.0 of WebScience to npm

### ISSUE THREAD

**Issue by rhelmer** [mozilla-rally/web-science#34]
We need to figure out a basic release process and publish an initial version to npm. Currently that will be named `@mozilla/web-science` (configurable in `package.json`).

**Comment by hamilton** [comment]
This is a duplicate of #3 – will close that issue in favor of this one. Ideally we should use semantic versioning making this `0.1.0`

**Comment by rhelmer** [comment]
Closed by https://github.com/mozilla-rally/web-science/pull/38

**Comment by rhelmer** [comment]
Created a new release + tag: https://github.com/mozilla-rally/web-science/releases/tag/v0.1.0
