### ISSUE TITLE
Refactor dataAnalysis to remove study-specific code

### ISSUE THREAD

**Issue by jonathanmayer** [mozilla-rally/web-science#36]
The current implementation of `dataAnalysis` is closely linked to the news and disinformation study. I'm going to temporarily remove the module so it isn't a blocker. We can discuss here what—if anything—we want to retain from the module in WebScience.

**Comment by jonathanmayer** [comment]
After mulling this over, I think what we should provide is a `registerWorker` function in `scheduling` (see the similar function in `pageText`) that provides the `onIdleDaily` and `onIdleWeekly` events inside a Web Worker. That addresses the core use case for `dataAnalysis`, allowing researchers to schedule data analysis off the main thread when the browser is idle. @akohlbre, sound reasonable?

**Comment by akohlbre** [comment]
Yes, that sounds like what we need. It would be nice to let the caller of `registerWorker` listen for messages from the worker -- I think we need `worker.onmessage` (and `onerror`) for that. I could see letting the caller pass in a callback for that, or just handing them the worker back so they can do it themselves.

**Comment by jonathanmayer** [comment]
Closing this since #61 tracks where we landed on Web Workers, for now.
