### ISSUE TITLE
Improve survey popup appearance

### ISSUE THREAD

**Issue by jonathanmayer** [mozilla-rally/web-science#59]
The current survey popup is... not pretty. Screenshot below. If Mozilla folks could help, much appreciated.

<img width="1160" alt="not-awesome survey" src="https://user-images.githubusercontent.com/382615/114313257-cdfad480-9ac3-11eb-9e78-605a5e659336.png">

**Comment by changecourse** [comment]
Is this the existing doorhanger for the Political & COVID-19 News study?

**Comment by changecourse** [comment]
We could utilize some of the existing doorhanger styles to make this more congruent with the rest of the experience: 
<img width="1200" alt="add-on_ survey prompt" src="https://user-images.githubusercontent.com/6164801/114431824-2b9f2780-9b7d-11eb-9cfc-2ab5e6f40f65.png">

Some outstanding questions: 

1. when a study add-on is installed, I'd like to confirm that it doesn't get added to the toolbar by default (cc @rhelmer) 
2. can we push communication prompts from our Rally add-on instead of the study add-ons? (may need to be a future enhancement, but it would be nice if the platform drove these types of messages, based on messaging coming from study add-ons)

**Comment by jonathanmayer** [comment]
> can we push communication prompts from our Rally add-on instead of the study add-ons? (may need to be a future enhancement, but it would be nice if the platform drove these types of messages, based on messaging coming from study add-ons)

💯 

We've been soliciting survey participation through our study extension because there isn't an alternative. Channeling survey requests through the Rally UX would be ideal. See:

* https://github.com/mozilla-rally/rally-core-addon/issues/168
* https://github.com/mozilla-rally/rally-core-addon/issues/177

**Comment by kartkand** [comment]
Updated the current survey popup appearance. The icon and prompt are configurable through the options parameter passed into `setSurvey` in `userSurvey`.

Available survey with icon
![Screen Shot 2021-04-19 at 11 27 00 AM](https://user-images.githubusercontent.com/25372358/115262525-a1b60800-a102-11eb-8d01-292bbf28dda8.png)

Available survey without icon
![Screen Shot 2021-04-19 at 11 26 13 AM](https://user-images.githubusercontent.com/25372358/115262548-a5e22580-a102-11eb-8a52-362a0ff096ca.png)

No survey with icon
![Screen Shot 2021-04-19 at 11 22 48 AM](https://user-images.githubusercontent.com/25372358/115262562-a975ac80-a102-11eb-8c76-a7f3a60b426e.png)

No survey without icon
![Screen Shot 2021-04-19 at 11 23 43 AM](https://user-images.githubusercontent.com/25372358/115262576-ad093380-a102-11eb-993e-f020f4d4be3c.png)

**Comment by rhelmer** [comment]
> We could utilize some of the existing doorhanger styles to make this more congruent with the rest of the experience:
> <img alt="add-on_ survey prompt" width="1200" src="https://user-images.githubusercontent.com/6164801/114431824-2b9f2780-9b7d-11eb-9cfc-2ab5e6f40f65.png">
> 
> Some outstanding questions:
> 
>     1. when a study add-on is installed, I'd like to confirm that it doesn't get added to the toolbar by default (cc @rhelmer)

Yes, showing toolbar buttons is something add-ons need to do explicitly.

>     2. can we push communication prompts from our Rally add-on instead of the study add-ons? (may need to be a future enhancement, but it would be nice if the platform drove these types of messages, based on messaging coming from study add-ons)

As Jonathan mentioned yes this is something we could provide.
